AC_INIT(configure.in)

AM_CONFIG_HEADER(config.h)
AM_INIT_AUTOMAKE(wsdl, 0.1)

AC_LANG_CPLUSPLUS
AC_PROG_CXX
AM_PROG_LIBTOOL

CURLLIBNAME="curl"
AC_ARG_WITH(curl-lib,
AC_HELP_STRING([--with-curl-lib=libname],[Specify name of dynamic curl lib file]), [CURLLIBNAME="$withval"])
AC_SUBST(CURLLIBNAME)

AC_ARG_ENABLE(xcurl,
     [  --enable-xcurl    Turn on curl extention],
     [case "${enableval}" in
       yes) xcurl=true ;;
       no)  xcurl=false ;;
       *) AC_MSG_ERROR(bad value ${enableval} for --enable-xcurl) ;;
     esac],[xcurl=false])
     AM_CONDITIONAL(XCURL, test x$xcurl = xtrue)

AC_OUTPUT(Makefile src/Makefile src/wsdl/Makefile src/test/Makefile include/Makefile)
